name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: 'latest'}
#         - {compiler: intel, version: '2025.0'}
#         - {compiler: intel-classic, version: '2021.10'}
#         - {compiler: nvidia-hpc, version: '25.1'}
#         - {compiler: lfortran, version: '0.45.0'}
#       exclude:
#         - os: macos-latest
#           toolchain: {compiler: intel}
#         - os: macos-latest
#           toolchain: {compiler: intel-classic}
#         - os: macos-latest
#           toolchain: {compiler: nvidia-hpc}
#         - os: windows-latest
#           toolchain: {compiler: nvidia-hpc}

    steps:
      - name: Getting Repository
        uses: actions/checkout@v5  
      - name: Setup Fortran
        uses: fortran-lang/setup-fortran@v1.8.0
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - name: Run make
        run: make insolation